name: ci
on:
  push:

defaults:
  run:
    shell: bash --noprofile --norc -euo pipefail {0}

concurrency: ci-${{ github.ref }}-${{ github.workflow }}

permissions:
  contents: read

env:
  TF_CLI_ARGS: -no-color

jobs:
  terraform:
    name: Terraform
    timeout-minutes: 30
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          fetch-depth: 0
          persist-credentials: 'false'

      - name: Install tools
        uses: jdx/mise-action@e3d7b8d67a7958d1207f6ed871e83b1ea780e7b0 # v3.3.1
        with:
          version: 2025.8.7
          install: true # run mise install
          cache: true

      - name: Load tflint plugin cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ~/.tflint.d/plugins
          key: ${{ runner.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

      - name: Lint module
        run: make lint

      - name: Initialize module
        run: make init

      - name: Check formatting
        run: make fmt-check

      - name: Check documentation
        run: make docs-check

      - name: Validate configuration
        run: make validate

  github-actions-workflows:

    name: GitHub Actions
    timeout-minutes: 30
    runs-on: ubuntu-24.04
    permissions:
      security-events: write # allow zizmor to upload security audit results
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          persist-credentials: 'false'

      - name: lint workflows
        uses: raven-actions/actionlint@fd1b743b251ce06a07f899ad2e53e238e94df30d #

      - name: audit workflows
        uses: zizmorcore/zizmor-action@e673c3917a1aef3c65c972347ed84ccd013ecda4 # v0.2.0

  release:
    name: Create GitHub release
    timeout-minutes: 30
    runs-on: ubuntu-24.04
    if: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
    needs: [terraform, github-actions-workflows]

    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          persist-credentials: 'false'

      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 24.10.0

      - name: conditionally semantic release
        run: make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
