name: ci
on:
  push:

defaults:
  run:
    shell: bash --noprofile --norc -euo pipefail {0}

concurrency: ci-${{ github.ref }}-${{ github.workflow }}

permissions:
  contents: read

env:
  TF_CLI_ARGS: -no-color

jobs:
  terraform:
    name: Terraform
    timeout-minutes: 30
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: 'false'

      - name: Install tools
        uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3.6.1
        with:
          version: 2025.12.11
          install: true # run mise install
          cache: true

      - name: Load tflint plugin cache
        uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
        with:
          path: ~/.tflint.d/plugins
          key: ${{ runner.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

      - name: Lint module
        run: make lint

      - name: Initialize module
        run: make init

      - name: Check formatting
        run: make fmt-check

      - name: Check documentation
        run: make docs-check

      - name: Validate configuration
        run: make validate

  github-actions-workflows:

    name: GitHub Actions
    timeout-minutes: 30
    runs-on: ubuntu-24.04
    permissions:
      security-events: write # allow zizmor to upload security audit results
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: 'false'

      - name: lint workflows
        uses: raven-actions/actionlint@fd1b743b251ce06a07f899ad2e53e238e94df30d #

      - name: audit workflows
        uses: zizmorcore/zizmor-action@135698455da5c3b3e55f73f4419e481ab68cdd95 # v0.4.1

  release:
    name: Create GitHub release
    timeout-minutes: 30
    runs-on: ubuntu-24.04
    if: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
    needs: [terraform, github-actions-workflows]

    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: 'false'

      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: 24.13.1

      - name: conditionally semantic release
        run: make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
